// Sample restaurant data, replace with your own data

let cityRestaurants = {
  "Surrey/Langley": {
    Italian: [
      "Bozzini's Restaurant - Greek, Indian, Italian - Rating: 4.0",
      "Pasta Timo - Rating: 4.6",
      "Aaron's Pizza Restaurant - Rating: 4.1",
      "Red Rose Restaurant - Rating: 4.1",
      "A-1 Pizza - Rating: 4.5",
      "LaDamico Pizza - Rating: 4.5",
      "Liberty Kitchen - Rating: 4.3",
      "Venetis Pizza - Rating: 3.9",
      "Famoso Italian Pizzeria - Guildford - Rating: 4.2",
      "Famoso Italian Pizzeria - Morgan Crossing - Rating: 3.9",
      "The Italian Osteria & Cheesebar - Rating: 4.2",
      "Dawood's Meat & Pizza - Rating: 4.5",
      "Captain's Oven Pizza Surrey - Rating: 4.8",
      "Olive Garden Italian Restaurant - Rating: 4.2",
      "Royal Oak Restaurant - Rating: 4.0",
      "Porto Fino Express - Pizza, Greek & Italian ( South Surrey / White Rock ) - Rating: 4.5",
      "Pasta Polo Langley - Rating: 4.0",
      "Pasta Vino Trattoria & Bar - No reviews",
      "The Old Spaghetti Factory (Langley) - Rating: 4.3",
      "Artusi Pizza and Pasta - Rating: 4.3",
      "Artusi Pizza and Pasta - Rating: 4.3",
      "Papa Joe's Pizza - Rating: 4.0",
      "Firepit pizza - Rating: 3.7",
      "La Baia Italian Restaurant Ltd. - Rating: 4.0",
      "Kwantlen Pizza Fleetwood Fraser Hwy - Rating: 4.6",
      "184 Pizza Corner - Rating: 4.3",
      "Great Pizza 2 For 1 - Rating: 3.7",
      "Freshslice Pizza - Rating: 4.3",
      "Aroma Pizza - Rating: 3.0",
      "Parms Pizza Factory - Rating: 4.8",
    ],
    Mexican: [
      "Guacamole Mexican Grill - Rating: 4.6",
      "Salsa & Guacamole - Rating: 4.6",
      "Ay Chihuahua Mexican Food - Rating: 4.7",
      "Miltomates Taqueria - Rating: 4.8",
      "La Conquistadora - Rating: 4.1",
      "Sal y Limon - Rating: 4.3",
      "Taqueria Jalisco Restaurant - Rating: 4.7",
      "Quesada Burritos & Tacos - Rating: 4.1",
      "Chipotle Mexican Grill - Rating: 4.0",
      "Mucho Burrito Fresh Mexican Grill - Rating: 3.9",
      "Quesada Burritos & Tacos - Rating: 3.8",
      "Quesada Burritos & Tacos - Rating: 4.0",
      "TacoTime Scott Road - Rating: 3.9",
      "barBURRITO - Rating: 4.3",
      "Taco Bell - Rating: 3.0",
      "Quesada Burritos & Tacos - Rating: 4.2",
      "Taco Bell - Rating: 3.3",
      "Chipotle Mexican Grill - Rating: 2.7",
      "Quesada Burritos & Tacos - Rating: 4.0",
      "Chipotle Mexican Grill - Rating: 2.9",
      "Quesada Burritos & Tacos - Rating: 3.9",
    ],
    Chinese: [
      "The Momo Grill Nepali Kitchen - Rating: 4.5",
      "On Yuen Chinese Restaurant - Rating: 4.0",
      "Inchin's Bamboo Garden- Surrey - Rating: 4.2",
      "Jade Valley Chinese Restaurant - Rating: 3.6",
      "Dragon Wok | Indian-Style Chinese Cuisine - Rating: 4.3",
      "Lucky Horse Chinese Restaurant - Rating: 3.5",
      "King Do Seafood Restaurant - Rating: 3.8",
      "Chuihong - Rating: 4.4",
      "SANHAO BBQ 川湘缘 - Rating: 4.1",
      "Kwan Kee Noodle House - Rating: 4.1",
      "Golden Medal Restaurant - Rating: 3.9",
      "BBQ King Delight - Rating: 4.1",
      "Ken's Cafe & Restaurant - Rating: 4.5",
      "Chili House Restaurant - Rating: 4.2",
      "Chan's kitchen - Rating: 4.1",
      "Ming Fung Restaurant - Rating: 4.1",
      "New Town Bakery & Restaurant - Rating: 4.0",
      "Green Lettuce - Rating: 4.1",
      "Wok One Kitchen - Rating: 4.2",
      "ChongQing on Scott Road - Rating: 4.1",
      "Tae Yang Gak - Rating: 4.3",
      "Tae Yang Gak - Rating: 4.3",
      "Dragon's Chop Suey House - Rating: 4.2",
      "KUNG PAO WOK - Rating: 2.5",
      "Neptune Wonton Noodle - Rating: 3.8",
      "Rickshaw Chinese Food - Rating: 2.8",
      "Top Kings Restaurant & Cafe - Rating: 3.8",
      "Golden Panda Restaurant - Rating: 3.7",
      "Taste of Himalayas - Rating: 4.6",
      "Spice of Nepal Restaurant - Rating: 4.2",
      "Lee's Express Chinese Food - Rating: 3.2",
      "Neptune Palace Seafood Restaurant (Surrey) - Rating: 3.7",
      "Bubble 88 - Rating: 4.1",
      "Manchu Wok - Rating: 3.4",
      "Kel-Fen's Kitchen Chinese Restaurant - Rating: 3.8",
      "Kathmandu Bar and Grill - Rating: 4.3",
      "味道重庆Don Asian Kitchen - Rating: 3.8",
      "Main Choice Chinese Restaurant (Free Mini Roll for Orders over $50 from Our Website!) - Rating: 4.1",
      "Dragon Village Restaurant & Won Ton House - Rating: 4.4",
      "海边人(白石店) Fishermans Chinese Fusion - Rating: 3.8",
    ],
    Sushi: [
      "Yoko Sushi & noodles - Rating: 4.3",
      "Sushi Zion - Rating: 4.6",
      "Sushi Shogun - Rating: 4.4",
      "Tobiko #1 Sushi - Rating: 4.2",
      "Aka Sushi in Surrey - Rating: 4.4",
      "Kyoto Sushi - Rating: 4.1",
      "Sushi California - Rating: 4.2",
      "Sushi Tengoku - Rating: 3.9",
      "Tawara - Rating: 4.3",
      "Maguro Japanese Restaurant - Rating: 3.8",
      "Umami Sushi Surrey - Rating: 4.4",
      "Isshin Sushi - Rating: 4.4",
      "Sushi Street - Rating: 4.2",
      "Village Sushi Restaurant - Rating: 4.3",
      "Nagoya Sushi - Rating: 4.4",
      "IKE Sushi - Rating: 4.7",
      "Fleetwood Sushi - Rating: 3.5",
      "Guildford Sushi House - Rating: 4.3",
      "Nordel Sushi - Rating: 3.9",
      "Sushi & Roll - Rating: 4.1",
      "The Jin Sushi - Rating: 4.3",
      "SUSHI PLUS - Rating: 4.3",
      "Red Shiso Sushi - Rating: 4.2",
      "Sushi Line Japanese Restaurant - Rating: 3.9",
      "Haru Sushi - Rating: 4.5",
      "Hanako Japanese Restaurant - Rating: 4.2",
      "Mauna Sushi - Rating: 4.6",
      "Kami Sushi - Rating: 4.4",
      "Migoto Sushi - Rating: 4.2",
      "Sushi Mori Japanese Restaurant - Rating: 4.3",
      "Ato Sushi Bar + Kitchen - Rating: 4.7",
      "Maguroguy Sushi & Grill Asian Cuisine - Rating: 4.1",
      "Ding Sushi Japanese Restaurant - Rating: 4.3",
      "Sushi Topia - Rating: 4.5",
    ],
    Indian: [
      "The Momo Grill Nepali Kitchen - Rating: 4.5",
      "The Great Indian Cuisine - Rating: 4.4",
      "Thali Indian cuisine - Rating: 4.1",
      "Chef's Kebab - Rating: 4.2",
      "Swagat Indian Sweets & Restaurant - Rating: 4.1",
      "Royal Choice Indian Cuisine - Rating: 4.3",
      "Spice Kings Bistro - Rating: 4.1",
      "ICE AND SPICE INDIAN RESTAURANT - Rating: 4.6",
      "Diamond Sweets Restaurant - Rating: 3.1",
      "Rasoi Fine Indian Cuisine - Rating: 4.4",
      "Chatora Indian Restaurant - Rating: 4.5",
      "Mahaveer Chef's Choice - Rating: 3.9",
      "Curry Lounge Indian Restaurant. - Rating: 4.1",
      "Green Indian Cuisine - Rating: 4.5",
      "DHABA DOSA Indian Grill - Rating: 4.4",
      "Spice6 Pizza&Curry Indian Restaurant. - Rating: 4.3",
      "Kerala Kitchen - Rating: 4.4",
      "Planet India Restaurant - Rating: 3.8",
      "Spice of Nepal Restaurant - Rating: 4.2",
      "Desi Bites Restaurants Dine In & Takeout Juice Bar - Rating: 4.0",
      "Jaipur Indian Cuisine - Rating: 3.5",
      "Ambar Surrey Restaurant & Dhaba - Rating: 4.2",
      "Dhoom Restaurant - Rating: 3.8",
      "Spice 72 Indian Restaurant & Lounge - Rating: 4.1",
      "Bikaner Indian Sweets - Rating: 4.1",
      "Doon Spice & Curry Restaurant - Rating: 4.3",
      "Diamond Sweets & Restaurant - Rating: 3.3",
      "Mayuri Indian Cuisine - Rating: 4.2",
      "Indian Haveli - Rating: 3.6",
      "Spice Club Indian Cuisine - Rating: 4.7",
      "Bharat Sweets & Restaurant - Rating: 3.8",
      "Mahek Indian Restaurant and Lounge - Rating: 3.8",
      "The Indian Club - Rating: 4.4",
      "Spice of Punjab - Rating: 4.0",
      "Curry and Kabab - Rating: 4.3",
      "Saini Sweets Restaurant - Rating: 3.9",
      "Royal Indian Chef and Sweets - Rating: 4.0",
      "Simply Curries Inc - Rating: 4.7",
      "Payal Chaat House and Restaurant - Rating: 4.0",
      "Ustaad G76 Indian Cuisine - Rating: 4.6",
      "Sam's Chaat House - Rating: 4.2",
      "Ustaad G Scott Road - Rating: 4.5",
      "Navraj Sweets & Restaurant - Rating: 4.2",
      "Krishna's Dosa Grill - Rating: 4.2",
      "Delight Indian Bistro Now The Back Room - Rating: 4.2",
      "Anjali's dosa garden - Rating: 4.1",
      "Showshaa - The Modern Taproom - Rating: 4.3",
      "Maharani Sweets & Restaurant - Rating: 4.2",
      "Royal Chaska Indian Restro & Bar - Rating: 4.3",
      "USTAAD G76 SURREY CENTRAL - Rating: 4.9",
      "Sahota’s Live Grill - Rating: 4.2",
      "Apna Chaat House - Rating: 3.9",
      "Pizza85 and Curry House Indian Restaurant - Rating: 4.1",
      "Taste of Himalayas - Rating: 4.6",
      "Flavo Grill Restaurant - Rating: 4.8",
      "Khana Peena 24 hrs Indian Buffet Everyday - Rating: 3.9",
      "ANMOL SWEETS RESTAURANT - Rating: 4.6",
      "Clove - The Art of Dining - Rating: 4.2",
      "The Samosa House (128 St & 88 Ave) - Rating: 4.3",
      "Panorama Indian Lounge (Dosa Lounge) - Rating: 4.7",
    ],
    Any: [
      "Bozzini's Restaurant - Greek, Indian, Italian - Rating: 4.0",
      "Pasta Timo - Rating: 4.6",
      "Aaron's Pizza Restaurant - Rating: 4.1",
      "Red Rose Restaurant - Rating: 4.1",
      "A-1 Pizza - Rating: 4.5",
      "LaDamico Pizza - Rating: 4.5",
      "Liberty Kitchen - Rating: 4.3",
      "Venetis Pizza - Rating: 3.9",
      "Famoso Italian Pizzeria - Guildford - Rating: 4.2",
      "Famoso Italian Pizzeria - Morgan Crossing - Rating: 3.9",
      "The Italian Osteria & Cheesebar - Rating: 4.2",
      "Dawood's Meat & Pizza - Rating: 4.5",
      "Captain's Oven Pizza Surrey - Rating: 4.8",
      "Olive Garden Italian Restaurant - Rating: 4.2",
      "Royal Oak Restaurant - Rating: 4.0",
      "Porto Fino Express - Pizza, Greek & Italian ( South Surrey / White Rock ) - Rating: 4.5",
      "Pasta Polo Langley - Rating: 4.0",
      "Pasta Vino Trattoria & Bar - No reviews",
      "The Old Spaghetti Factory (Langley) - Rating: 4.3",
      "Artusi Pizza and Pasta - Rating: 4.3",
      "Artusi Pizza and Pasta - Rating: 4.3",
      "Papa Joe's Pizza - Rating: 4.0",
      "Firepit pizza - Rating: 3.7",
      "La Baia Italian Restaurant Ltd. - Rating: 4.0",
      "Kwantlen Pizza Fleetwood Fraser Hwy - Rating: 4.6",
      "184 Pizza Corner - Rating: 4.3",
      "Great Pizza 2 For 1 - Rating: 3.7",
      "Freshslice Pizza - Rating: 4.3",
      "Aroma Pizza - Rating: 3.0",
      "Parms Pizza Factory - Rating: 4.8",

      "Guacamole Mexican Grill - Rating: 4.6",
      "Salsa & Guacamole - Rating: 4.6",
      "Ay Chihuahua Mexican Food - Rating: 4.7",
      "Miltomates Taqueria - Rating: 4.8",
      "La Conquistadora - Rating: 4.1",
      "Sal y Limon - Rating: 4.3",
      "Taqueria Jalisco Restaurant - Rating: 4.7",
      "Quesada Burritos & Tacos - Rating: 4.1",
      "Chipotle Mexican Grill - Rating: 4.0",
      "Mucho Burrito Fresh Mexican Grill - Rating: 3.9",
      "Quesada Burritos & Tacos - Rating: 3.8",
      "Quesada Burritos & Tacos - Rating: 4.0",
      "TacoTime Scott Road - Rating: 3.9",
      "barBURRITO - Rating: 4.3",
      "Taco Bell - Rating: 3.0",
      "Quesada Burritos & Tacos - Rating: 4.2",
      "Taco Bell - Rating: 3.3",
      "Chipotle Mexican Grill - Rating: 2.7",
      "Quesada Burritos & Tacos - Rating: 4.0",
      "Chipotle Mexican Grill - Rating: 2.9",
      "Quesada Burritos & Tacos - Rating: 3.9",

      "The Momo Grill Nepali Kitchen - Rating: 4.5",
      "On Yuen Chinese Restaurant - Rating: 4.0",
      "Inchin's Bamboo Garden- Surrey - Rating: 4.2",
      "Jade Valley Chinese Restaurant - Rating: 3.6",
      "Dragon Wok | Indian-Style Chinese Cuisine - Rating: 4.3",
      "Lucky Horse Chinese Restaurant - Rating: 3.5",
      "King Do Seafood Restaurant - Rating: 3.8",
      "Chuihong - Rating: 4.4",
      "SANHAO BBQ 川湘缘 - Rating: 4.1",
      "Kwan Kee Noodle House - Rating: 4.1",
      "Golden Medal Restaurant - Rating: 3.9",
      "BBQ King Delight - Rating: 4.1",
      "Ken's Cafe & Restaurant - Rating: 4.5",
      "Chili House Restaurant - Rating: 4.2",
      "Chan's kitchen - Rating: 4.1",
      "Ming Fung Restaurant - Rating: 4.1",
      "New Town Bakery & Restaurant - Rating: 4.0",
      "Green Lettuce - Rating: 4.1",
      "Wok One Kitchen - Rating: 4.2",
      "ChongQing on Scott Road - Rating: 4.1",
      "Tae Yang Gak - Rating: 4.3",
      "Tae Yang Gak - Rating: 4.3",
      "Dragon's Chop Suey House - Rating: 4.2",
      "KUNG PAO WOK - Rating: 2.5",
      "Neptune Wonton Noodle - Rating: 3.8",
      "Rickshaw Chinese Food - Rating: 2.8",
      "Top Kings Restaurant & Cafe - Rating: 3.8",
      "Golden Panda Restaurant - Rating: 3.7",
      "Taste of Himalayas - Rating: 4.6",
      "Spice of Nepal Restaurant - Rating: 4.2",
      "Lee's Express Chinese Food - Rating: 3.2",
      "Neptune Palace Seafood Restaurant (Surrey) - Rating: 3.7",
      "Bubble 88 - Rating: 4.1",
      "Manchu Wok - Rating: 3.4",
      "Kel-Fen's Kitchen Chinese Restaurant - Rating: 3.8",
      "Kathmandu Bar and Grill - Rating: 4.3",
      "味道重庆Don Asian Kitchen - Rating: 3.8",
      "Main Choice Chinese Restaurant (Free Mini Roll for Orders over $50 from Our Website!) - Rating: 4.1",
      "Dragon Village Restaurant & Won Ton House - Rating: 4.4",
      "海边人(白石店) Fishermans Chinese Fusion - Rating: 3.8",

      "Yoko Sushi & noodles - Rating: 4.3",
      "Sushi Zion - Rating: 4.6",
      "Sushi Shogun - Rating: 4.4",
      "Tobiko #1 Sushi - Rating: 4.2",
      "Aka Sushi in Surrey - Rating: 4.4",
      "Kyoto Sushi - Rating: 4.1",
      "Sushi California - Rating: 4.2",
      "Sushi Tengoku - Rating: 3.9",
      "Tawara - Rating: 4.3",
      "Maguro Japanese Restaurant - Rating: 3.8",
      "Umami Sushi Surrey - Rating: 4.4",
      "Isshin Sushi - Rating: 4.4",
      "Sushi Street - Rating: 4.2",
      "Village Sushi Restaurant - Rating: 4.3",
      "Nagoya Sushi - Rating: 4.4",
      "IKE Sushi - Rating: 4.7",
      "Fleetwood Sushi - Rating: 3.5",
      "Guildford Sushi House - Rating: 4.3",
      "Nordel Sushi - Rating: 3.9",
      "Sushi & Roll - Rating: 4.1",
      "The Jin Sushi - Rating: 4.3",
      "SUSHI PLUS - Rating: 4.3",
      "Red Shiso Sushi - Rating: 4.2",
      "Sushi Line Japanese Restaurant - Rating: 3.9",
      "Haru Sushi - Rating: 4.5",
      "Hanako Japanese Restaurant - Rating: 4.2",
      "Mauna Sushi - Rating: 4.6",
      "Kami Sushi - Rating: 4.4",
      "Migoto Sushi - Rating: 4.2",
      "Sushi Mori Japanese Restaurant - Rating: 4.3",
      "Ato Sushi Bar + Kitchen - Rating: 4.7",
      "Maguroguy Sushi & Grill Asian Cuisine - Rating: 4.1",
      "Ding Sushi Japanese Restaurant - Rating: 4.3",
      "Sushi Topia - Rating: 4.5",

      "The Momo Grill Nepali Kitchen - Rating: 4.5",
      "The Great Indian Cuisine - Rating: 4.4",
      "Thali Indian cuisine - Rating: 4.1",
      "Chef's Kebab - Rating: 4.2",
      "Swagat Indian Sweets & Restaurant - Rating: 4.1",
      "Royal Choice Indian Cuisine - Rating: 4.3",
      "Spice Kings Bistro - Rating: 4.1",
      "ICE AND SPICE INDIAN RESTAURANT - Rating: 4.6",
      "Diamond Sweets Restaurant - Rating: 3.1",
      "Rasoi Fine Indian Cuisine - Rating: 4.4",
      "Chatora Indian Restaurant - Rating: 4.5",
      "Mahaveer Chef's Choice - Rating: 3.9",
      "Curry Lounge Indian Restaurant. - Rating: 4.1",
      "Green Indian Cuisine - Rating: 4.5",
      "DHABA DOSA Indian Grill - Rating: 4.4",
      "Spice6 Pizza&Curry Indian Restaurant. - Rating: 4.3",
      "Kerala Kitchen - Rating: 4.4",
      "Planet India Restaurant - Rating: 3.8",
      "Spice of Nepal Restaurant - Rating: 4.2",
      "Desi Bites Restaurants Dine In & Takeout Juice Bar - Rating: 4.0",
      "Jaipur Indian Cuisine - Rating: 3.5",
      "Ambar Surrey Restaurant & Dhaba - Rating: 4.2",
      "Dhoom Restaurant - Rating: 3.8",
      "Spice 72 Indian Restaurant & Lounge - Rating: 4.1",
      "Bikaner Indian Sweets - Rating: 4.1",
      "Doon Spice & Curry Restaurant - Rating: 4.3",
      "Diamond Sweets & Restaurant - Rating: 3.3",
      "Mayuri Indian Cuisine - Rating: 4.2",
      "Indian Haveli - Rating: 3.6",
      "Spice Club Indian Cuisine - Rating: 4.7",
      "Bharat Sweets & Restaurant - Rating: 3.8",
      "Mahek Indian Restaurant and Lounge - Rating: 3.8",
      "The Indian Club - Rating: 4.4",
      "Spice of Punjab - Rating: 4.0",
      "Curry and Kabab - Rating: 4.3",
      "Saini Sweets Restaurant - Rating: 3.9",
      "Royal Indian Chef and Sweets - Rating: 4.0",
      "Simply Curries Inc - Rating: 4.7",
      "Payal Chaat House and Restaurant - Rating: 4.0",
      "Ustaad G76 Indian Cuisine - Rating: 4.6",
      "Sam's Chaat House - Rating: 4.2",
      "Ustaad G Scott Road - Rating: 4.5",
      "Navraj Sweets & Restaurant - Rating: 4.2",
      "Krishna's Dosa Grill - Rating: 4.2",
      "Delight Indian Bistro Now The Back Room - Rating: 4.2",
      "Anjali's dosa garden - Rating: 4.1",
      "Showshaa - The Modern Taproom - Rating: 4.3",
      "Maharani Sweets & Restaurant - Rating: 4.2",
      "Royal Chaska Indian Restro & Bar - Rating: 4.3",
      "USTAAD G76 SURREY CENTRAL - Rating: 4.9",
      "Sahota’s Live Grill - Rating: 4.2",
      "Apna Chaat House - Rating: 3.9",
      "Pizza85 and Curry House Indian Restaurant - Rating: 4.1",
      "Taste of Himalayas - Rating: 4.6",
      "Flavo Grill Restaurant - Rating: 4.8",
      "Khana Peena 24 hrs Indian Buffet Everyday - Rating: 3.9",
      "ANMOL SWEETS RESTAURANT - Rating: 4.6",
      "Clove - The Art of Dining - Rating: 4.2",
      "The Samosa House (128 St & 88 Ave) - Rating: 4.3",
      "Panorama Indian Lounge (Dosa Lounge) - Rating: 4.7",
    ],
  },
  "Burnaby/New West": {
    Italian: [
      "Trattoria Burnaby - Rating: 3.9",
      "Anton's Pasta Bar - Rating: 4.4",
      "La Forchetta - Rating: 4.4",
      "Basil Pasta Bar - Rating: 4.1",
      "Cioffi’s Cucina - Rating: 4.4",
      "La Fontana - Rating: 4.7",
      "L'Artista Italian Restaurant - Rating: 4.5",
      "Portobello Restaurant Burnaby - Rating: 4.4",
      "Claudio's Ristorante - Rating: 4.2",
      "Amorosa Pasta House - Rating: 4.0",
      "Baci Ristorante - Rating: 4.3",
      "Circolo Ristorante Italiano - Rating: 4.6",
      "Famoso Italian Pizzeria - Solo - Rating: 4.5",
      "Sopra Sotto Pizzeria - Rating: 4.4",
      "Argo Greek Cuisine Pizza & Pasta - Rating: 4.4",
      "Little Billy's - Rating: 4.3",
      "La Piazza Dario - Rating: 4.3",
      "Ramie's Greek Restaurant - Rating: 4.1",
      "Ragazzi Pizza Co - Rating: 4.4",
      "Stan's Pizza Joint - Rating: 4.4",
      "Artusi Restaurant - Rating: 4.4",
      "Wild Flour Pizza Co - Rating: 4.8",
      "Piva Modern Italian - Rating: 4.4",
      "HellCrust Pizza- Burnaby - Rating: 3.8",
      "Casa Eatalia - Rating: 4.9",
      "Pizza Pizza - Rating: 4.1",
      "Gino's Restaurant - Rating: 4.2",
      "The Old Spaghetti Factory (New Westminster) - Rating: 4.3",
    ],
    Mexican: [
      "Don Oso's Restaurant - Burnaby - Rating: 4.3",
      "La Taqueria Pinche Taco Shop - Rating: 4.4",
      "Mucho Burrito Fresh Mexican Grill - Rating: 4.0",
      "Quesada Burritos & Tacos - Rating: 3.9",
      "Quesada Burritos & Tacos - Rating: 4.1",
      "Chronic Tacos - Rating: 3.3",
      "Quesada Burritos & Tacos - Rating: 4.1",
      "Quesada Burritos & Tacos - Rating: 4.0",
      "El Comal - Rating: 4.4",
      "Good Taco - Rating: 4.0",
      "El Chilakil by Body Balance Bar - Rating: 4.6",
      "Olivo Cafe - Rating: 4.6",
      "Tacofino Metrotown - Rating: 5.0",
      "The Taco Factory - Rating: 4.3",
      "Border Burrito - Rating: 4.4",
      "Vallarta's Mexican Restaurant - Rating: 4.1",
      "Taqueria Playa Tropical - Rating: 4.3",
      "Ole Ole Mexican Cuisine - Rating: 4.4",
      "Sal y Limon - Rating: 4.4",
      "El Santo - Rating: 4.2",
      "Taco Del Mar - Rating: 4.0",
      "Los Guerreros Mexican Food Products - Rating: 4.2",
    ],
    Chinese: [
      "Chili Dragon Chinese Restaurant (Take Out Only) - Rating: 4.4",
      "Fung May Chinese Cuisine - Rating: 4.0",
      "Double One Chinese Restaurant - Rating: 4.2",
      "Shanghai Dimsum House - Rating: 4.1",
      "Grand Chinese Restaurant - Rating: 4.1",
      "North Burnaby Wonton House - Rating: 3.7",
      "Peking Restaurant - Rating: 4.0",
      "Glorious Bao - Rating: 4.3",
      "Marble House Eatery - Rating: 4.3",
      "Burnaby Palace Restaurant - Rating: 4.1",
      "Garlic & Chili Restaurant - Rating: 4.2",
      "Manchu Wok - Rating: 3.1",
      "Shanghai Fortune Cuisine - Rating: 3.9",
      "On On Wonton House - Rating: 3.6",
      "The Boss Restaurant - Rating: 3.5",
      "Deer Lake Wonton Restaurant - Rating: 4.0",
      "Jade Palace Chinese Restaurant - Rating: 3.8",
      "ChongQing on Kingsway - Rating: 3.9",
      "Yan's Garden 潮樓 - Rating: 4.1",
      "Mr. Ho Wonton House - Rating: 3.9",
      "Yunshang Rice Noodle - Rating: 3.8",
      "Old Xian's Food - Rating: 3.7",
      "May Rice Roll & Congee Chinese Restaurant 恩平肠粉美食 - Rating: 3.8",
      "Szechuan Cuisine - Rating: 3.6",
      "Manchu Wok - Rating: 2.6",
      "Mui Garden Restaurant - Rating: 3.7",
      "The One Restaurant - Rating: 3.9",
      "Bamboo Garden Restaurant - Rating: 3.1",
      "Dinesty Dumpling House - Rating: 3.7",
      "New Lakeview Seafood & Wonton - Rating: 4.0",
      "Jin Jiang Shanghai Restaurant - Rating: 3.8",
      "S & W Pepper House - Rating: 3.6",
    ],
    Sushi: [
      "Sushi On Burnaby - Rating: 4.8",
      "Green Leaf Sushi l Burnaby - Rating: 4.3",
      "Hon Sushi - Rating: 4.0",
      "Sushi U Burnaby - Rating: 4.4",
      "Sushi Yoi - Rating: 4.0",
      "Sushi S Japanese Restaurant - Rating: 4.4",
      "Sushi UOmo - Rating: 4.3",
      "Sushi Modo_Burnaby - Rating: 4.4",
      "Nao Sushi - Rating: 3.9",
      "Shen Sushi - Rating: 4.5",
      "SUSHI BOX - Rating: 4.6",
      "Takara Sushi - Rating: 4.5",
      "Sushi Garden Brentwood - Rating: 3.7",
      "Gaya Sushi - Rating: 3.9",
      "Hong Sushi - Rating: 4.1",
      "Sushi Garden Highgate - Rating: 3.9",
      "Sushi Oyama - Rating: 3.8",
      "Osaka Sushi - Rating: 3.9",
      "Togo Sushi - Rating: 3.7",
      "Makoto Japanese Restaurant - Rating: 4.1",
      "Nu Sushi Bar - Rating: 3.9",
      "Take Sushi Japanese Restaurant - Rating: 4.3",
      "Sushi Giwa - Rating: 4.2",
      "Sushi Garden Metro - Rating: 3.8",
      "Sushimoto - Rating: 4.3",
      "Sushi Q Tea Cafe - Rating: 4.1",
      "Hiro Sushi - Rating: 4.1",
      "Togo Sushi SFU - Rating: 4.1",
      "Tentatsu Japanese Restaurant Burnaby - Rating: 3.7",
      "Salmon Wave - Rating: 4.8",
      "Okoman Restaurant - Rating: 3.9",
      "Fresh Box Sushi - Rating: 4.0",
      "FusionCore Japanese Eatery - Rating: 4.4",
      "Kawawa Japanese Restaurant - Rating: 2.8",
      "Taku Japanese Kitchen - Rating: 4.8",
      "Sushi Toki - Rating: 4.3",
      "Ajishou Brentwood Japanese Restaurant - Rating: 3.9",
      "Sushi Bar Kilala - Rating: 4.7",
      "Toyo Sushi Japanese Restaurant - Rating: 4.7",
      "Kiku Sushi Metrotown - Rating: 3.6",
      "Yugo Roll and Bowl - Rating: 3.7",
      "Umi Sushi Express - Rating: 3.4",
      "Club Salmon Sushi Bar and Bistro - Rating: 4.6",
      "Isami Sushi - Rating: 4.1",
      "Sushi Q - Rating: 3.5",
      "Kazu Japanese Restaurant - Rating: 4.6",
      "Sushia sushi - Rating: 3.6",
      "Koya Japan - Rating: 3.8",
      "Watashi Sushi & Kitchen - Rating: 4.9",
      "Bento Sushi - Rating: 3.3",
      "Phở Japolo - Rating: 4.3",
      "Joy Sushi - Rating: 3.8",
      "Tairyou Ichiba - Rating: 4.0",
    ],
    Indian: [
      "Desi Turka Indian Cuisine-Burnaby - Rating: 4.4",
      "Saffron Indian Cuisine - Rating: 4.1",
      "Indian Bombay Bistro - Rating: 4.1",
      "Agra Tandoori Restaurant - Rating: 4.1",
      "Manjal South Indian Kitchen - Rating: 4.4",
      "Tasty Planet Indian Cuisine - Rating: 4.4",
      "Chakra Indian Restaurant - Rating: 4.2",
      "Agra Tandoori House - Rating: 4.2",
      "Royal Paan - Rating: 3.7",
      "Chettinad Dosa Palace - Rating: 3.7",
      "Agra Sweets - Rating: 4.0",
      "Baba Sweets & Restaurant - Rating: 3.8",
      "Curry Express - Rating: 2.3",
      "Curry Express - Rating: 3.6",
      "Govinda's Dining - Rating: 4.7",
      "Cayenne Bistro and Grill - Rating: 4.8",
      "James Street Café & Grill - Rating: 3.9",
      "Kurry Wala Indian cuisine - Rating: 4.8",
      "Indian Wok - Rating: 4.4",
      "Mr. Pan Pizza - Rating: 3.9",
      "Mr. Pan Pizza - Rating: 3.9",
      "Go Curry Go! - Rating: 4.3",
      "LR Pizza & Curry Ltd - Rating: 4.4",
      "Indian Courtyard Restaurant - Rating: 4.3",
      "Khurana Kitchen - No reviews yet",
      "Dana Pani Indian Cuisine - Rating: 4.4",
      "Safari Snack House - Rating: 4.3",
      "Mumbaiyaa Street Foods - Rating: 4.9",
      "Donair Delight - Rating: 4.2",
      "Annapurna Ruchulu Inc. - Rating: 4.1",
      "Changos - Rating: 5.0",
      "VadaPav Mirchi By Geeta - Rating: 4.7",
      "Indian Village Eatery - Rating: 4.1",
      "Jambo Grill Tandoor & Paan House - Rating: 4.2",
      "The Indian Chefs Kitchen & Bar - Rating: 4.6",
      "D ROTI SHAK - Rating: 4.3",
      "Simba's Grill - Rating: 4.6",
      "Maple Mirchy - Temporarily closed",
      "House Of Dosas - Rating: 4.4",
      "Dosa Factory - Rating: 4.3",
    ],
    Any: [
      "Desi Turka Indian Cuisine-Burnaby - Rating: 4.4",
      "Saffron Indian Cuisine - Rating: 4.1",
      "Indian Bombay Bistro - Rating: 4.1",
      "Agra Tandoori Restaurant - Rating: 4.1",
      "Manjal South Indian Kitchen - Rating: 4.4",
      "Tasty Planet Indian Cuisine - Rating: 4.4",
      "Chakra Indian Restaurant - Rating: 4.2",
      "Agra Tandoori House - Rating: 4.2",
      "Royal Paan - Rating: 3.7",
      "Chettinad Dosa Palace - Rating: 3.7",
      "Agra Sweets - Rating: 4.0",
      "Baba Sweets & Restaurant - Rating: 3.8",
      "Curry Express - Rating: 2.3",
      "Curry Express - Rating: 3.6",
      "Govinda's Dining - Rating: 4.7",
      "Cayenne Bistro and Grill - Rating: 4.8",
      "James Street Café & Grill - Rating: 3.9",
      "Kurry Wala Indian cuisine - Rating: 4.8",
      "Indian Wok - Rating: 4.4",
      "Mr. Pan Pizza - Rating: 3.9",
      "Mr. Pan Pizza - Rating: 3.9",
      "Go Curry Go! - Rating: 4.3",
      "LR Pizza & Curry Ltd - Rating: 4.4",
      "Indian Courtyard Restaurant - Rating: 4.3",
      "Khurana Kitchen - No reviews yet",
      "Dana Pani Indian Cuisine - Rating: 4.4",
      "Safari Snack House - Rating: 4.3",
      "Mumbaiyaa Street Foods - Rating: 4.9",
      "Donair Delight - Rating: 4.2",
      "Annapurna Ruchulu Inc. - Rating: 4.1",
      "Changos - Rating: 5.0",
      "VadaPav Mirchi By Geeta - Rating: 4.7",
      "Indian Village Eatery - Rating: 4.1",
      "Jambo Grill Tandoor & Paan House - Rating: 4.2",
      "The Indian Chefs Kitchen & Bar - Rating: 4.6",
      "D ROTI SHAK - Rating: 4.3",
      "Simba's Grill - Rating: 4.6",
      "Maple Mirchy - Temporarily closed",
      "House Of Dosas - Rating: 4.4",
      "Dosa Factory - Rating: 4.3",
      "Sushi On Burnaby - Rating: 4.8",
      "Green Leaf Sushi l Burnaby - Rating: 4.3",
      "Hon Sushi - Rating: 4.0",
      "Sushi U Burnaby - Rating: 4.4",
      "Sushi Yoi - Rating: 4.0",
      "Sushi S Japanese Restaurant - Rating: 4.4",
      "Sushi UOmo - Rating: 4.3",
      "Sushi Modo_Burnaby - Rating: 4.4",
      "Nao Sushi - Rating: 3.9",
      "Shen Sushi - Rating: 4.5",
      "SUSHI BOX - Rating: 4.6",
      "Takara Sushi - Rating: 4.5",
      "Sushi Garden Brentwood - Rating: 3.7",
      "Gaya Sushi - Rating: 3.9",
      "Hong Sushi - Rating: 4.1",
      "Sushi Garden Highgate - Rating: 3.9",
      "Sushi Oyama - Rating: 3.8",
      "Osaka Sushi - Rating: 3.9",
      "Togo Sushi - Rating: 3.7",
      "Makoto Japanese Restaurant - Rating: 4.1",
      "Nu Sushi Bar - Rating: 3.9",
      "Take Sushi Japanese Restaurant - Rating: 4.3",
      "Sushi Giwa - Rating: 4.2",
      "Sushi Garden Metro - Rating: 3.8",
      "Sushimoto - Rating: 4.3",
      "Sushi Q Tea Cafe - Rating: 4.1",
      "Hiro Sushi - Rating: 4.1",
      "Togo Sushi SFU - Rating: 4.1",
      "Tentatsu Japanese Restaurant Burnaby - Rating: 3.7",
      "Salmon Wave - Rating: 4.8",
      "Okoman Restaurant - Rating: 3.9",
      "Fresh Box Sushi - Rating: 4.0",
      "FusionCore Japanese Eatery - Rating: 4.4",
      "Kawawa Japanese Restaurant - Rating: 2.8",
      "Taku Japanese Kitchen - Rating: 4.8",
      "Sushi Toki - Rating: 4.3",
      "Ajishou Brentwood Japanese Restaurant - Rating: 3.9",
      "Sushi Bar Kilala - Rating: 4.7",
      "Toyo Sushi Japanese Restaurant - Rating: 4.7",
      "Kiku Sushi Metrotown - Rating: 3.6",
      "Yugo Roll and Bowl - Rating: 3.7",
      "Umi Sushi Express - Rating: 3.4",
      "Club Salmon Sushi Bar and Bistro - Rating: 4.6",
      "Isami Sushi - Rating: 4.1",
      "Sushi Q - Rating: 3.5",
      "Kazu Japanese Restaurant - Rating: 4.6",
      "Sushia sushi - Rating: 3.6",
      "Koya Japan - Rating: 3.8",
      "Watashi Sushi & Kitchen - Rating: 4.9",
      "Bento Sushi - Rating: 3.3",
      "Phở Japolo - Rating: 4.3",
      "Joy Sushi - Rating: 3.8",
      "Tairyou Ichiba - Rating: 4.0",
      "Trattoria Burnaby - Rating: 3.9",
      "Anton's Pasta Bar - Rating: 4.4",
      "La Forchetta - Rating: 4.4",
      "Basil Pasta Bar - Rating: 4.1",
      "Cioffi’s Cucina - Rating: 4.4",
      "La Fontana - Rating: 4.7",
      "L'Artista Italian Restaurant - Rating: 4.5",
      "Portobello Restaurant Burnaby - Rating: 4.4",
      "Claudio's Ristorante - Rating: 4.2",
      "Amorosa Pasta House - Rating: 4.0",
      "Baci Ristorante - Rating: 4.3",
      "Circolo Ristorante Italiano - Rating: 4.6",
      "Famoso Italian Pizzeria - Solo - Rating: 4.5",
      "Sopra Sotto Pizzeria - Rating: 4.4",
      "Argo Greek Cuisine Pizza & Pasta - Rating: 4.4",
      "Little Billy's - Rating: 4.3",
      "La Piazza Dario - Rating: 4.3",
      "Ramie's Greek Restaurant - Rating: 4.1",
      "Ragazzi Pizza Co - Rating: 4.4",
      "Stan's Pizza Joint - Rating: 4.4",
      "Artusi Restaurant - Rating: 4.4",
      "Wild Flour Pizza Co - Rating: 4.8",
      "Piva Modern Italian - Rating: 4.4",
      "HellCrust Pizza- Burnaby - Rating: 3.8",
      "Casa Eatalia - Rating: 4.9",
      "Pizza Pizza - Rating: 4.1",
      "Gino's Restaurant - Rating: 4.2",
      "The Old Spaghetti Factory (New Westminster) - Rating: 4.3",
      "Don Oso's Restaurant - Burnaby - Rating: 4.3",
      "La Taqueria Pinche Taco Shop - Rating: 4.4",
      "Mucho Burrito Fresh Mexican Grill - Rating: 4.0",
      "Quesada Burritos & Tacos - Rating: 3.9",
      "Quesada Burritos & Tacos - Rating: 4.1",
      "Chronic Tacos - Rating: 3.3",
      "Quesada Burritos & Tacos - Rating: 4.1",
      "Quesada Burritos & Tacos - Rating: 4.0",
      "El Comal - Rating: 4.4",
      "Good Taco - Rating: 4.0",
      "El Chilakil by Body Balance Bar - Rating: 4.6",
      "Olivo Cafe - Rating: 4.6",
      "Tacofino Metrotown - Rating: 5.0",
      "The Taco Factory - Rating: 4.3",
      "Border Burrito - Rating: 4.4",
      "Vallarta's Mexican Restaurant - Rating: 4.1",
      "Taqueria Playa Tropical - Rating: 4.3",
      "Ole Ole Mexican Cuisine - Rating: 4.4",
      "Sal y Limon - Rating: 4.4",
      "El Santo - Rating: 4.2",
      "Taco Del Mar - Rating: 4.0",
      "Los Guerreros Mexican Food Products - Rating: 4.2",
    ],
  },
};

function showRandomRestaurant() {
  const cityDropdown = document.getElementById("cityDropdown");
  const genresDropdown = document.getElementById("genresDropdown");
  const selectedCity = cityDropdown.value;
  const selectedGenre = genresDropdown.value;
  const restaurants = cityRestaurants[selectedCity][selectedGenre];

  if (!restaurants) {
    alert("Please select a valid city.");
    return;
  }

  const randomIndex = Math.floor(Math.random() * restaurants.length);
  const randomRestaurant = restaurants[randomIndex];

  const resultContainer = document.getElementById("result");
  resultContainer.innerHTML = `<p>🍴Random Restaurant in ${selectedCity} for ${selectedGenre}: <strong>${randomRestaurant}⭐</strong></p>`;
}
